"""Initialize complete SimCore schema

Revision ID: 631b1b11b436
Revises: 
Create Date: 2026-06-06 21:17:24.346925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2 


# revision identifiers, used by Alembic.
revision: str = '631b1b11b436'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kml_zones',
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('zone_name', sa.String(), nullable=True),
    sa.Column('polygon_coordinates', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('zone_id')
    )
    # REMOVED the redundant idx_kml_zones_polygon_coordinates create_index line here
    op.create_index(op.f('ix_kml_zones_zone_name'), 'kml_zones', ['zone_name'], unique=True)
    
    op.create_table('radar_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('track_id', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('direction', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('zone_name', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_radar_events_event_type'), 'radar_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_radar_events_track_id'), 'radar_events', ['track_id'], unique=False)
    
    op.create_table('system_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('log_level', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    
    op.create_table('spider_transmissions',
    sa.Column('transmission_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('transmission_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['radar_events.event_id'], ),
    sa.PrimaryKeyConstraint('transmission_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spider_transmissions')
    op.drop_table('system_logs')
    op.drop_index(op.f('ix_radar_events_track_id'), table_name='radar_events')
    op.drop_index(op.f('ix_radar_events_event_type'), table_name='radar_events')
    op.drop_table('radar_events')
    op.drop_index(op.f('ix_kml_zones_zone_name'), table_name='kml_zones')
    # REMOVED the redundant idx_kml_zones_polygon_coordinates drop_index line here
    op.drop_table('kml_zones')
    # ### end Alembic commands ###

    