"""Initial Stage 2 Build

Revision ID: 824161a556bf
Revises: 
Create Date: 2026-06-08 21:30:13.545003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '824161a556bf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_templates',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('subsystem', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('default_severity', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('template_id')
    )
    op.create_table('kml_exports',
    sa.Column('export_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('export_id')
    )
    op.create_table('kml_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_name', sa.String(), nullable=True),
    sa.Column('polygon_coordinates', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    #op.create_index('idx_kml_zones_polygon_coordinates', 'kml_zones', ['polygon_coordinates'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_kml_zones_id'), 'kml_zones', ['id'], unique=False)
    op.create_index(op.f('ix_kml_zones_zone_name'), 'kml_zones', ['zone_name'], unique=True)
    op.create_table('radar_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('track_id', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('direction', sa.Float(), nullable=True),
    sa.Column('zone_name', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_radar_events_event_type'), 'radar_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_radar_events_track_id'), 'radar_events', ['track_id'], unique=False)
    op.create_table('sensors',
    sa.Column('sensor_id', sa.UUID(), nullable=False),
    sa.Column('subsystem', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('sensor_id')
    )
    op.create_index(op.f('ix_sensors_subsystem'), 'sensors', ['subsystem'], unique=False)
    op.create_table('scenario_definitions',
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=True),
    sa.Column('sensors_included', sa.JSON(), nullable=True),
    sa.Column('severity_level', sa.String(), nullable=True),
    sa.Column('buffer_zone_meters', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('active_kml_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['active_kml_id'], ['kml_zones.id'], ),
    sa.PrimaryKeyConstraint('scenario_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('spider_delivery_log',
    sa.Column('transmission_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('target_ip', sa.String(), nullable=True),
    sa.Column('target_port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.Column('transmission_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('response_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['radar_events.event_id'], ),
    sa.PrimaryKeyConstraint('transmission_id')
    )
    op.create_table('scenario_executions',
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('scenario_id', sa.UUID(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario_definitions.scenario_id'], ),
    sa.PrimaryKeyConstraint('execution_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenario_executions')
    op.drop_table('spider_delivery_log')
    op.drop_table('scenario_definitions')
    op.drop_index(op.f('ix_sensors_subsystem'), table_name='sensors')
    op.drop_table('sensors')
    op.drop_index(op.f('ix_radar_events_track_id'), table_name='radar_events')
    op.drop_index(op.f('ix_radar_events_event_type'), table_name='radar_events')
    op.drop_table('radar_events')
    op.drop_index(op.f('ix_kml_zones_zone_name'), table_name='kml_zones')
    op.drop_index(op.f('ix_kml_zones_id'), table_name='kml_zones')
    op.drop_index('idx_kml_zones_polygon_coordinates', table_name='kml_zones', postgresql_using='gist')
    op.drop_table('kml_zones')
    op.drop_table('kml_exports')
    op.drop_table('alert_templates')
    # ### end Alembic commands ###
